version: 0.2

phases:

  pre_build:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version

  build:
    commands:
      - terraform init 
      # - terraform apply -var-file dev.tfvars -auto-approve
      - terraform destroy -var-file dev.tfvars -auto-approve
